// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSX5iD2tueFBT9BD2QJOdyEOxTeEvLXIY',
    appId: '1:505086886661:web:fc9e68d23a1dbebad0ad6c',
    messagingSenderId: '505086886661',
    projectId: 'chat-app-69418',
    authDomain: 'chat-app-69418.firebaseapp.com',
    storageBucket: 'chat-app-69418.appspot.com',
    measurementId: 'G-TP18V9J8GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_V8OJ8XR1vL0plf1oFvNm8CK473C-YA',
    appId: '1:505086886661:android:9692d48f72b0fbfed0ad6c',
    messagingSenderId: '505086886661',
    projectId: 'chat-app-69418',
    storageBucket: 'chat-app-69418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL2IAtjYd3q-z8M4MCCRYSSLoDMSMLE6s',
    appId: '1:505086886661:ios:cdce7526fd6cb47cd0ad6c',
    messagingSenderId: '505086886661',
    projectId: 'chat-app-69418',
    storageBucket: 'chat-app-69418.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL2IAtjYd3q-z8M4MCCRYSSLoDMSMLE6s',
    appId: '1:505086886661:ios:dbba616b636030c3d0ad6c',
    messagingSenderId: '505086886661',
    projectId: 'chat-app-69418',
    storageBucket: 'chat-app-69418.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
